### ISSUE TITLE
What's the prompt template?

### ISSUE THREAD

**Issue by lxa-g** [ngoanpv/llama2_vietnamese#1]
I did not get good results when trying llama2_vietnamese. I tried with both:
1. Llama2 template: `final_llm_prompt = f'<s>[INST] \n\n{user_input}[/INST]'`
2. No template: `final_llm_prompt = f'{user_input}'`

Output:
```
Việt Nam có bao nhiêu tỉnh?

Llama2_vietnamese:  Tượng tặm mọi bấy nại dày
```

Can you pls help me how to get good results from this model using Vietnamese?

**Comment by ngoanpv** [comment]
This prompt include the system prompt and user prompt, please check this snippet code at the template.py file https://github.com/ngoanpv/llama2_vietnamese/blob/main/src/llama2_vi/models/templates/template.py :

```register_template(
    name="llama2_vi",
    prefix=[
        "<<SYS>>\n{{system}}\n<</SYS>>\n\n"
    ],
    prompt=[
        "[INST] {{query}} [/INST] "
    ],
    system="You are a helpful assistant. Bạn là một trợ lí hữu ích.",
    sep=[]
) 
```

**Comment by lxa-g** [comment]
Thank you for the help. 
I used the quantized 4bit model GGUF from TheBloke, so was not sure what's the prompt template.

I tried with this template, results look better now.

```
[INST] <<SYS>>
You are a helpful assistant. Bạn là một trợ lí hữu ích.
<</SYS>>

Hà Nội mùa thu thế nào?[/INST]
```

```
Hà Nội mùa thu thế nào?

Thời gian cuối của mùa thu ở Hà Nội có thể được chia vào ba giai đoạn. Phần lớn, từ tháng 10 đến tháng 12, thời tiết dễ nhìn thấy hơn là mát hơn thông thường và trung bình. Trong thời gian các lớp kéo dài từ 8 giờ đến 20 giờ, nhiệt độ đạt mức hơi cao hơn so với tháng 10. Tháng 9 có khí hậu xấu hơn so với giai đoạn trước, nhiệt độ cũng bị giảm mát hơn hoặc thời tiết dễ quá phù hợp. Tháng ba có lúc thay đổi tần suất gió và chính xác của nó, cũng như giảm mát cao hơn so với dòng phong bình thường.
```

Keep up the great work!
Thank you.

**Comment by ngoanpv** [comment]
Glad to see it work as expected,
I'll be working on the upcoming version shortly. If you have high-quality datasets and would like to contribute them to this project for the benefit of the community, please feel free to do so. 
Your contributions are greatly appreciated. Thanks!

**Comment by lxa-g** [comment]
I don't own any datasets myself. Below are some repos I found that looks great. 
Maybe you already know about these repos. However, I still post here in case it's useful.

https://github.com/binhvq/news-corpus
https://github.com/telexyz/data
https://github.com/telexyz/GPT4VN/blob/main/data/sample.jsonl

https://www.kaggle.com/datasets/iambestfeeder/10000-vietnamese-books/
https://huggingface.co/datasets/truongpdd/vietnamese_poetry
https://huggingface.co/truongpdd
